 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app2
  name: app2-deployment
spec:
  replicas: 2                
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: app1-deployment
spec:
  replicas: 2      
                  
